version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5001"
    depends_on:
      - redis
    networks:
      - my_net
  redis:
    image: redis:3.2.11
    networks:
      - my_net
# this is a comment
networks:
  my_net:
    driver: bridge
