version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline version 2.1'
      - run:
          name: Code has arrived
          command: |
            ls -la
            echo '^^^That should look familiar^^^'



# version: 2
# jobs:
#   build:
#     working_directory: /dockerapp
#     docker:
#       - image: docker:17.05.0-ce-git
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Install dependencies
#           command: |
#             apk add --no-cache py-pip=9.0.0-r1
#             pip install docker-compose==1.15.0
#       - run:
#           name: Run tests
#           command: |
#             docker-compose up -d
#             docker-compose run flask-app python test.py
